<?php

use Database\Seeders\PagesSeeder;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        // Remove all old pages (including soft-deleted ones) and reset IDs.
        Schema::disableForeignKeyConstraints();
        DB::table('pages')->truncate();
        Schema::enableForeignKeyConstraints();

        // Recreate the pages defined in the seeder.
        (new PagesSeeder())->run();
    }

    public function down(): void
    {
        // No rollback: pages can be regenerated by running the seeder again.
    }
};
